package com.morph.markdown.demo

object MarkdownFixtures {
	fun create(validUri: String, invalidUri: String): List<String> {
		return listOf(
			"# Streaming Markdown on Android\n\n",
			"Model text arrives in chunks. This paragraph has **bold**, *emphasis*, ",
			"`inline code`, [a link](https://example.com), and inline math: ",
			"\$e^{i\\pi}+1=0\$",
			" and display math follows.\n\n",
			"$$\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}$$\n\n",
			"## Lists and tasks\n\n",
			"1. Ordered item one\n",
			"2. Ordered item two with nested bullets\n",
			"   - nested bullet A\n",
			"   - nested bullet B\n\n",
			"## Marker styles\n\n",
			"- level 1 uses disc marker\n",
			"  - level 2 uses circle marker\n",
			"    - level 3 uses square marker\n",
			"      - level 4 cycles marker styles\n\n",
			"- [x] parse CommonMark/GFM task lists\n",
			"- [ ] migrate renderer into production UI\n",
			"- [ ] preserve streaming updates on partial blocks\n",
			"- [ ] a long task item that wraps to a second line so checkbox alignment can be checked against the first line of text\n\n",
			"> A block quote can arrive while the model is still generating. ",
			"It should stay readable and not collapse the layout.\n\n",
			"```kotlin\n",
			"val view\t= MorphMarkdownView(context)\n",
			"view.append(chunk, final = false)\n",
			"view.mathRenderer\t= MathJaxMathRenderer(context)\n",
			"```\n\n",
			"---\n\n",
			"## Dynamic table\n\n",
			"| feature | status |\n",
			"|:---|:---:|\n",
			"| CommonMark blocks | ok |\n",
			"| GFM tasklist | ok |\n",
			"| mathjax-c bitmap | ok |\n",
			"| dynamic table growth | ok |\n",
			"| inline formula \$a^2+b^2=c^2\$ | rendered in cell |\n",
			"| valid image ![generated]($validUri) | decoded bitmap in cell |\n",
			"| invalid image ![missing]($invalidUri) | error placeholder in cell |\n",
			"| code `cell.value()` and [link](https://example.com) | mixed inline |\n",
			"| tab text | key\tvalue\twith tabs |\n",
			"| long cell | this is a deliberately long table value that should wrap inside the cell while the table can still scroll horizontally |\n\n",
			"HTML sample: <span>treated as text by policy</span>\n\n",
			"Valid image:\n\n![generated demo]($validUri \"generated\")\n\n",
			"Invalid image:\n\n![missing demo]($invalidUri \"missing\")\n\n",
			"# 中文排版 HetiLike\n\n",
			"这是一段用于检查中文阅读排版的长段落。今天发布 MorphMarkdown v1.0，",
			"它支持 Android/iOS、MathJax-C、GFM table 和 task list。中文与 English、",
			"数字 12345、`inlineCode()`、[链接](https://example.com) 混排时，",
			"需要保持舒适的行高、合理的中西文间距，以及不会挤在一起的视觉节奏。\n\n",
			"## 二级标题：中文标题间距\n\n",
			"中文段落通常比英文更依赖稳定的行高和段落节奏。HetiLike 主题会使用 16sp 正文、",
			"约 1.5 倍行高、偏阅读型的标题层级，并让表格、列表、引用都跟正文网格靠齐。\n\n",
			"### 三级标题：列表与任务\n\n",
			"- 第一层无序列表使用实心圆，适合普通条目。\n",
			"  - 第二层列表使用空心圆，用于补充说明。\n",
			"    - 第三层列表使用方块，层级需要清楚但不能太重。\n",
			"- 中英混排 item：MorphMarkdown 渲染中文、English 和 2026 年的数字。\n\n",
			"1. 有序列表第一项，文本比较长时应该自然换行。\n",
			"2. 有序列表第二项，包含嵌套项目。\n",
			"   - 嵌套项目 A：中文与 Android 混排。\n",
			"   - 嵌套项目 B：中文与 iOS 混排。\n\n",
			"- [x] 支持中文 HetiLike 主题\n",
			"- [ ] 检查中文 task list 的 checkbox 与文字基线\n",
			"- [ ] 这是一条很长的中文任务，用于验证多行换行后，复选框仍然对齐第一行文字而不是挤到中间\n\n",
			"> 引用块也需要中文阅读节奏。它不应该像代码块一样紧凑，而是应该保留足够呼吸感，",
			"并且在流式输出时保持布局稳定。\n\n",
			"```text\n",
			"中文代码块不参与中西文 spacing：MorphMarkdown\tHetiLike\t中文排版\n",
			"```\n\n",
			"## 中文表格\n\n",
			"| 场景 | 效果 |\n",
			"|:---|:---|\n",
			"| 中文长文本 | 这是一段故意写得比较长的中文表格内容，用来验证单元格换行、行高、padding 和横向滚动是否仍然稳定。 |\n",
			"| 表格内公式 | 勾股定理 \$a^2+b^2=c^2\$ 应该可以在中文单元格中渲染。 |\n",
			"| 表格内高公式 | 求根公式 \$\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}\$ 只应该撑高当前行，后面的中文仍然保持稳定换行。 |\n",
			"| 表格内有效图片 | ![generated]($validUri) |\n",
			"| 表格内无效图片 | ![missing]($invalidUri) |\n",
			"| 中英混排 | MorphMarkdown SDK 在 Android 和 iOS 上复用同一份 IR。 |\n\n",
			"---\n\n",
			"#### 四级标题\n\n",
			"收尾段落：中文排版不只是换字体，还包括字号、行高、段落间距、列表缩进、",
			"表格 padding、代码字号和混排 spacing 的整体组合。\n"
		)
	}
}
